/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmistoreclient.ui.tabs;

import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmistoreclient.helper.RMIStoreClientHelper;
import rmistoreclient.interfaces.BalanceDisplayer;
import rmistoreclient.interfaces.Callback;

/**
 *
 * @author davidsoendoro
 */
public class RMIStoreClientAccountPanel extends RMIStoreClientGenericTab implements BalanceDisplayer, Callback {

    /**
     * Creates new form RMIStoreClientBuyPanel
     */
    public RMIStoreClientAccountPanel() {
        tabName = "Account";
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBalance = new javax.swing.JLabel();
        jLabelBalanceValue = new javax.swing.JLabel();

        jLabelBalance.setText("Balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBalanceValue)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBalance)
                    .addComponent(jLabelBalanceValue))
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelBalanceValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayBalance(double balance) {
        jLabelBalanceValue.setText(" $" + balance);
    }

    public void refreshBalance() {
        try {
            RMIStoreClientHelper.customerRemoteObj.callback = this;
            RMIStoreClientHelper.customerRemoteObj.checkBalance();
        } catch (RemoteException ex) {
            Logger.getLogger(RMIStoreClientAccountPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void doCallback(Object arguments) {
        if(arguments != null && arguments.getClass() == Double.class) {
            DecimalFormat df = new DecimalFormat("#.00");
            jLabelBalanceValue.setText(" $" + df.format(arguments));
        }
    }
}
