/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmistoreclient.ui.tabs.items;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmistore.commons.exceptions.Rejected;
import rmistore.commons.interfaces.Item;
import rmistoreclient.helper.RMIStoreClientHelper;

/**
 *
 * @author davidsoendoro
 */
public class RMIStoreClientSellItem extends javax.swing.JPanel {

    private Item item;
    
    /**
     * Creates new form RMIStoreClientBuyItem
     */
    public RMIStoreClientSellItem() {
        initComponents();
    }
    
    public RMIStoreClientSellItem(Item item) {
        this.item = item;
        
        initComponents();
        
        jLabelName.setText(item.getName());
        jLabelPrice.setText("$" + item.getPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jButtonRemove = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabelName.setText("Name");
        add(jLabelName);

        jLabelPrice.setText("$0.00");
        add(jLabelPrice);

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        add(jButtonRemove);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        try {
            RMIStoreClientHelper.customerRemoteObj.removeItem(this.item.getItemId());
        } catch (Rejected | RemoteException ex) {
            Logger.getLogger(RMIStoreClientSellItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    // End of variables declaration//GEN-END:variables
}
