/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmistoreclient.ui.tabs.items;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import rmistore.commons.interfaces.Item;
import rmistoreclient.helper.RMIStoreClientHelper;

/**
 *
 * @author davidsoendoro
 */
public class RMIStoreClientBuyItem extends javax.swing.JPanel {

    private Item item;
    
    /**
     * Creates new form RMIStoreClientBuyItem
     */
    public RMIStoreClientBuyItem() {
        initComponents();
    }
    
    public RMIStoreClientBuyItem(Item item) {
        this.item = item;
        
        initComponents();
        
        jLabelName.setText(item.getName() + " $" + item.getPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jButtonBuy = new javax.swing.JButton();
        jLabelWishPrice = new javax.swing.JLabel();
        jTextFieldWishPrice = new javax.swing.JTextField();
        jButtonWish = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabelName.setText("Name");
        add(jLabelName);

        jButtonBuy.setText("Buy");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });
        add(jButtonBuy);

        jLabelWishPrice.setText("Wish Price");
        add(jLabelWishPrice);
        add(jTextFieldWishPrice);

        jButtonWish.setText("Wish");
        jButtonWish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWishActionPerformed(evt);
            }
        });
        add(jButtonWish);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        try {
            RMIStoreClientHelper.customerRemoteObj.buyItem(this.item.getItemId());
        } catch (RemoteException ex) {
            Logger.getLogger(RMIStoreClientBuyItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void jButtonWishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWishActionPerformed
        String alert = "";
        try {
            Double.valueOf(jTextFieldWishPrice.getText());
        }
        catch (NumberFormatException ex) {
            alert += "Put correct number format!";
        }
        if(alert.length() > 0) {
            showMessageDialog(null, alert);  
        }
        else {
            try {
                RMIStoreClientHelper.customerRemoteObj.wishItem(this.item.getName(), 
                        Double.parseDouble(jTextFieldWishPrice.getText()));
            } catch (RemoteException ex) {
                Logger.getLogger(RMIStoreClientBuyItem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonWishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonWish;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelWishPrice;
    private javax.swing.JTextField jTextFieldWishPrice;
    // End of variables declaration//GEN-END:variables
}
