/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmistoreclient.ui.tabs.items;

/**
 *
 * @author davidsoendoro
 */
public class RMIStoreClientBuyItem extends javax.swing.JPanel {

    /**
     * Creates new form RMIStoreClientBuyItem
     */
    public RMIStoreClientBuyItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jButtonBuy = new javax.swing.JButton();
        jLabelWishPrice = new javax.swing.JLabel();
        jTextFieldWishPrice = new javax.swing.JTextField();
        jButtonWish = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout());

        jLabelName.setText("Name");
        add(jLabelName);

        jButtonBuy.setText("Buy");
        add(jButtonBuy);

        jLabelWishPrice.setText("Wish Price");
        add(jLabelWishPrice);
        add(jTextFieldWishPrice);

        jButtonWish.setText("Wish");
        add(jButtonWish);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonWish;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelWishPrice;
    private javax.swing.JTextField jTextFieldWishPrice;
    // End of variables declaration//GEN-END:variables
}
